% https://github.com/mrzamaniiii/Time-Domain-Back-Projection-Method
% Time Domain Back Projection TDBP
%clear all
%close all;
format long
if (exist('b210tdbp')==0) b210tdbp=1;end
if (exist('Nr')==0) Nr= 2501;end   % from range compression: number of range positions
if (exist('P')==0) P = 2301;end    % from range compression: number of satellite positions

if (b210tdbp==1)
% receiver dependent
  load b210_kpos.mat
  fs= 22;     % bandwidh MHz
  load S_2501_2301_b210.mat  % load S and kindx
  sat=load('satpos_b210-2.txt'); % sat relative coordinates wrt receivers
  sat=sat(kindx,:);
else
  load max2771_kpos.mat
  fs= 24;     % bandwidh MHz
  load S_2501_2301_max2771.mat
  sat=load('satpos_max2771-2.txt'); % sat relative coordinates wrt receivers
  sat=sat(kindx,:);
end
% end receiver dependent

c = 300;    % light speed m/us
fc= 1229;   % center freq MHz

Y31N=5237467; % ENSMM UTM31N
X31N=726480;
Ymin=-7000;
Ymax=7000;
Xmin=-1000;
Xmax=8000;

dX=10  % resolution (m)
dY=10
hasdem=1;

if (hasdem==1)
  pkg load mapping
  if (exist('../DEM5mx5m.tif')==2) dem=rasterread('../DEM5mx5m.tif');end
  if (exist('../../DEM5mx5m.tif')==2) dem=rasterread('../../DEM5mx5m.tif');end
  if (exist('dem')==0) printf("DEM not found\n");exit();end
  m=dem.data;
  k=find(m<0); m(k)=0;  % remove NaN
  % crop DEM
  x=linspace(dem.bbox(1,1),dem.bbox(2,1),size(m)(2));
  k=find((x>=X31N+Xmin)&(x<=X31N+Xmax));
  m=m(:,k);
  y=linspace(dem.bbox(1,2),dem.bbox(2,2),size(m)(1));
  k=find((y>=Y31N+Ymin)&(y<=Y31N+Ymax));
  m=m(k,:);
  newX=linspace(1,size(m)(2),(Xmax-Xmin)/dX);
  newY=linspace(1,size(m)(1),(Ymax-Ymin)/dY);
  [newX,newY]=meshgrid(newX,newY);
  dem=interp2(m, newX, newY);
%  imagesc(dem);
end

% generated by satpos.py
sat=[sat(:,2) sat(:,1) sat(:,3)];  % negative coordinate is X
recX=0;   % position of the satellite relative to the receiver
recY=0;
recZ=0;

% Time-domain signal upsampling (SAR imaging convergence)
% dtmax=phimax/(2pi.B)=8 ns v.s 1/fs=45 ns
% up_factor >= pi*B/fs/phimax (B rather than fc since baseband)
up_factor=8;  % fractional delay for fine phase estimate
Nr_up = Nr*up_factor;
S_tp_up=zeros(Nr_up, P);
for p = 1:P
    S(:,p)=S(:,p)-mean(S(:,p));
    tmp=ifft(ifftshift(S(:,p)),Nr_up);
    S_tp_up(:,p)=fftshift(tmp);
end
S_tp_up=S_tp_up-mean(S_tp_up,2);   % remove 0-azimuth line
tmp=mean(S_tp_up,2);   % remove 0-azimuth line
dt_up = 1/(fs*up_factor);
tau_up = [-(Nr_up-1)/2 : (Nr_up-1)/2].' * dt_up;
Rang_up = tau_up * c;

%% imaging grid relative to receiver
Nx=(Xmax-Xmin)/dX
Ny=(Ymax-Ymin)/dY
Xl= linspace(Xmin, Xmax, Nx);
Yl= linspace(Ymin, Ymax, Ny);
[X_grid, Y_grid]=meshgrid(Xl,Yl);
if (hasdem==1)
  Z_grid=dem; % zeros(Nx,Ny); % could be an elevation from DEM
else
  Z_grid=zeros(Ny,Nx);
end

%% TDBP
sigma = zeros(size(Z_grid));
for p = 1:P
  if (1==0) % if (mod(p,500)==0)
    figure
    sigma_dB = 20*log10(abs(sigma)/max(abs(sigma(:))));
    imagesc(sigma_dB);
    xlabel('X (m)'); ylabel('Y (m)');
    colorbar; colormap jet; 
    caxis([-55 0]);    
  end
  satX = sat(p, 1);
  satY = sat(p, 2);
  satZ = sat(p, 3);
  Rsr= sqrt((satX-recX)^2+(satY-recY)^2+(satZ-recZ)^2);
  Rst= sqrt((X_grid-satX).^2+(Y_grid-satY).^2+(Z_grid-satZ).^2);
  Rtr= sqrt((X_grid-recX).^2+(Y_grid-recY).^2+(Z_grid-recZ).^2);
  dR = Rst+Rtr-Rsr;  % range difference
  s_vals = interp1(Rang_up, S_tp_up(:, p), dR, 'linear', 0);
  s_vals = s_vals.*exp(j*2*pi*fc*dR/c);
  sigma = sigma+reshape(s_vals, size(X_grid));
end

figure
sigma_dB = 20*log10(abs(sigma)/max(abs(sigma(:))));
imagesc(Xl, Yl, sigma_dB);
xlabel('X (m)'); ylabel('Y (m)');
colorbar; colormap jet; axis xy;
caxis([-55 0]);    

if (b210tdbp==1)
  save -mat b210_tdbp.mat sigma
else
  save -mat max2771_tdbp.mat sigma
end
